### ISSUE TITLE
Server-Side Request Forgery in axios, it needs to be updated to 1.7.3

### ISSUE THREAD

**Issue by efstathiosntonas** [bugsnag/bugsnag-cli#131]
Axios versions >= 1.3.2, <= 1.7.3 have this issue: 

axios 1.7.2 allows SSRF via unexpected behavior where requests for path relative URLs get processed as protocol relative URLs.

this package uses ^1.6.2

**Comment by friday** [comment]
1.7.3 is still affected. There's no fixed version yet.

https://github.com/advisories/GHSA-8hc4-vh64-cxmj

**Comment by efstathiosntonas** [comment]
1.7.4 is out with the fix: https://github.com/axios/axios/releases/tag/v1.7.4

**Comment by hannah-smartbear** [comment]
Hi @efstathiosntonas,

Thanks for pointing this out.

We have gone ahead and [upgraded our Axios version to 1.7.4](https://github.com/bugsnag/bugsnag-cli/pull/133). This update should be available in the next version of `bugsnag-cli`.

**Comment by mclack** [comment]
Hi @efstathiosntonas 

We have released [v2.6.0 of `bugsnag-cli`](https://github.com/bugsnag/bugsnag-cli/releases/tag/v2.6.0), which now specifies `"axios": "^1.7.4"` as a dependency: https://github.com/bugsnag/bugsnag-cli/blob/v2.6.0/package.json#L23

Thanks again for raising this with us.
