### ISSUE TITLE
`upload dsym` doesn't work with target and schemes with spaces in their name

### ISSUE THREAD

**Issue by son-nguyen-goodnotes** [bugsnag/bugsnag-cli#134]
### Describe the bug
`upload dsym` doesn't work with target and schemes with spaces in their name

### Steps to reproduce
1. Create a target and scheme with spaces in its name, eg. "Sample project"
2. Build that scheme
3. Try to upload dSYM with `upload dsym`
4. Getting erorr: `Sample project is not a valid DWARF file`

### Environment
* `bugsnag-cli` version: 2.5.0
* Platform: iOS

<details><summary>Error messages:</summary>

```
[FATAL] Sample project is not a valid DWARF file
```
</details>

**Comment by clr182** [comment]
Hi son, 

Thanks for reaching out.

We do have an item on our backlog aimed at solving this issue with schemes that include whitespace. Unfortunately I do not have an ETA on the release of this functionality, however once we have more information we will be sure to update this github issue.

**Comment by RobertoSmartBear** [comment]
Hi @son-nguyen-goodnotes  👋🏻,

The issue you’ve reported was fixed and deployed in the latest release of bugsnag-cli [v2.6.0](https://github.com/bugsnag/bugsnag-cli/releases/tag/v2.6.0)

Thanks for letting us know about this and please let us know if you notice any further issues after upgrading to the latest version of the BugSnag CLI.
