### ISSUE TITLE
Cannot upload React Native source maps with a code-bundle-id 

### ISSUE THREAD

**Issue by ieatfood** [bugsnag/bugsnag-cli#139]
### Describe the bug
The upload server rejects request with the error `'appVersion' and 'appVersionCode' cannot be provided if 'codeBundleId' set` but the cli enforces appVersion and appVersionCode.

Even though I am not setting the versions explicitly, the cli requires the `--variant` argument and looks up the versions in the `AndroidManifest.xml` for that variant and includes them in the request.

### Steps to reproduce
1. Run `bugsnag-cli upload react-native-android`
2. With a `--code-bundle-id` argument

### Environment
* `bugsnag-cli` version: 2.6.0
* Platform: MacOS

### Example code snippet

```
node_modules/.bin/bugsnag-cli upload react-native-android \
  --api-key [redacted] \
  --variant internalRelease \
  --code-bundle-id internal-1726540387 \
  --bundle android/app/build/generated/assets/createBundleInternalReleaseJsAndAssets/index.android.bundle \
  --source-map android/app/build/generated/sourcemaps/react/internalRelease/index.android.bundle.map \
  --verbose
```

<details><summary>Error messages:</summary>

```
400 Bad Request: 'appVersion' and 'appVersionCode' cannot be provided if 'codeBundleId' set

# Output with --dry-run:
[INFO] Performing dry run - no data will be sent to BugSnag
[DEBUG] Found app manifest at: android/app/build/intermediates/merged_manifests/internalRelease/AndroidManifest.xml
[DEBUG] Using 6.25 as version name from AndroidManifest.xml
[DEBUG] Using 8390 as version code from AndroidManifest.xml
[INFO] (dryrun) Skipping upload of index.android.bundle.map to https://upload.bugsnag.com:443/react-native-source-map
[INFO] (dryrun) Upload payload:
[DEBUG] {
    "apiKey": "[redacted]",
    "appVersion": "6.25",
    "appVersionCode": "8390",
    "codeBundleId": "internal-1726540387",
    "platform": "android",
    "projectRoot": "."
}
```
</details>

**Comment by clr182** [comment]
Hi @ieatfood 

Could you please try uploading with the following cURL: 
```
bugsnag-cli upload react-native-android \
  --app-manifest path/to/custom/AndroidManifest.xml \
  --code-bundle-id internal-1726540387 \
  --bundle android/app/build/generated/assets/createBundleInternalReleaseJsAndAssets/index.android.bundle \
  --source-map android/app/build/generated/sourcemaps/react/internalRelease/index.android.bundle.map \
  --verbose
```

It seems like the `--variant` flag may be causing the CLI to automatically pull in the `appVersion` and `appVersionCode` from the `AndroidManifest.xml` file. You can try using the `--app-manifest` option instead of `--variant` and point it to a custom manifest file that either excludes those fields or provides values that won't trigger a conflict.

Alternatively, it may be worth removing the `appVersion` and `appVersionCode` in the manifest. As all that is needed for symbolication is the `code-bundle-id`.
