### ISSUE TITLE
Hardcoded asset path in react native android command

### ISSUE THREAD

**Issue by arthuralee** [bugsnag/bugsnag-cli#43]
### Describe the bug
The `upload react-native-android` command does not properly support variants other than `release`

"Release" is hardcoded here https://github.com/bugsnag/bugsnag-cli/blob/next/pkg/upload/react-native-android.go#L66

### Steps to reproduce
1. Have an android react native project that has a variant that is not named release (e.g. `alpha`)
2. Build the android project, e.g. `./gradlew ":app:bundleAlpha"`
3. Run `bugsnag-cli upload react-native-android`

### Environment
* `bugsnag-cli` version: 1.2.0 (consider adding a `--version` to the CLI to make it easier to check version?)
* Platform: macOS

**Comment by johnkiely1** [comment]
Hi @arthuralee, just to let you know we have updated this in v1.2.1 so you can now specify a non "release" variant when providing the bundle path as a flag to the CLI.
