### ISSUE TITLE
bugsnag-cli upload react-native-android  unable to find index.android.bundle on react native 0.72.1

### ISSUE THREAD

**Issue by sergeymild** [bugsnag/bugsnag-cli#45]
after update react native on version 0.72.1
while making command `bugsnag-cli upload react-native-android`
i always receive an error `unable to find index.android.bundle`

**Comment by johnkiely1** [comment]
Hi @sergeymild, this should now be fixed in [v1.2.1](https://github.com/bugsnag/bugsnag-cli/releases/tag/v1.2.1).

**Comment by sergeymild** [comment]
thanks, now it works
