### ISSUE TITLE
Suggestion: Do not modify package.json

### ISSUE THREAD

**Issue by arthuralee** [bugsnag/bugsnag-cli#47]
### Description
Would the team be open to removing any code that modifies `package.json`? It's not very typical to have a package installation modify `package.json` as a side effect. On top of that, the file is modified in a way that may not conform with the formatting styles of the codebase (e.g. tabs/spaces/space width). Overall, I don't want this behavior at all as I want control over what scripts I have in my package.json

**Describe the solution you'd like**
Remove this functionality completely, or make it opt-in (e.g. modify package.json only if running a script)

**Describe alternatives you've considered**

**Additional context**

**Comment by johnkiely1** [comment]
Hi @arthuralee, thanks for the suggestion. 

You make a good point so we are going to look into a refactor so the update to `package.json` is not performed by default.

We will update here when we have more information to share.

**Comment by johnkiely1** [comment]
Hi @arthuralee we have now released [v1.2.2](https://github.com/bugsnag/bugsnag-cli/releases/tag/v1.2.2) which avoids modifying the `package.json` file. Thanks again for raising this.
