### ISSUE TITLE
Installing bugsnag-cli fails when it is called many times within a short period of time

### ISSUE THREAD

**Issue by Frank3K** [bugsnag/bugsnag-cli#57]
### Describe the bug

We're trying to integrate bugsnag-cli as a post-publish script on [codemagic](https://codemagic.io/), such that we can use it to upload debug symbols. The installation fails often, but not always. At first, we assumed it was an issue at codemagic, but they investigated the issue (https://github.com/orgs/codemagic-ci-cd/discussions/2023) and came to the conclusion it was not within their infrastructure.

### Steps to reproduce

Consider this script:

```sh
#!/bin/sh
set -e

BUGSNAG_CLI_PATH=$HOME/.local/bugsnag/bin/bugsnag-cli

echo '--- Installing bugsnag-cli for:' $(uname)-$(uname -m) '---'
curl -o- https://raw.githubusercontent.com/bugsnag/bugsnag-cli/main/install.sh | bash
```

Example succesful run: 

```
--- Installing bugsnag-cli for: Darwin-arm64 ---
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4029  100  4029    0     0  35187      0 --:--:-- --:--:-- --:--:-- 36627
==> This script will install:
/Users/builder/.local/bugsnag/bin/bugsnag-cli
==> The following new directories will be created:
/Users/builder/.local/bugsnag/bin
==> Downloading and installing Bugsnag CLI...
#=#=#                                                                         
##O#-#                                                                        

                                                                           0.2%
                                                                           1.3%
########################################                                  55.8%
##########################################################                80.8%
######################################################################## 100.0%
Warning: /Users/builder/.local/bugsnag/bin is not in your PATH.
  Instructions on how to configure your shell for Bugsnag CLI
  can be found in the 'Next steps' section below.
==> Installation successful!
```

Example unsuccessful run: 

```sh
--- Installing bugsnag-cli for: Darwin-arm64 ---
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4029  100  4029    0     0  28944      0 --:--:-- --:--:-- --:--:-- 30067
==> This script will install:
/Users/builder/.local/bugsnag/bin/bugsnag-cli
==> The following new directories will be created:
/Users/builder/.local/bugsnag/bin
==> Downloading and installing Bugsnag CLI...
Failed to get download URL from https://api.github.com/repos/bugsnag/bugsnag-cli/releases/latest


Build failed :|
Step 9 script `Post-publish script` exited with status code 1
```

### Environment
* `bugsnag-cli` version: latest (install.sh)
* Platform: codemagic (reproducible locally)

### Example code snippet 

Included above.

**Comment by clr182** [comment]
Hi @Frank3K 
When you say reproducible locally, do you mean you have tested the cURL command in isolation outside of the codemagic platform? I have tried to reproduce this issue and have been unable to do so. Is this still a consistently flakey issue for you? If so, is this failing consistently at this line ```==> Downloading and installing Bugsnag CLI... Failed to get download URL from <https://api.github.com/repos/bugsnag/bugsnag-cli/releases/latest>``` ?  

It's also possible that the script is falling over sometimes  is due to an unexpected `uname` in the `install.sh` script. The `uname` variable looks to see if the operating system is either Linex or Darwin, some deviations on this may cause the script to fail inconsistently.

**Comment by Frank3K** [comment]
Thanks for fixing. We have integrated the new script in our codemagic flow and it works fine now 👍 .
